expression ::= [0]|([1-9][0-9]*)
ident     ::= [a-zA-Z_$][a-zA-Z0-9_$]*
string    ::= '"'ident'"'
local     ::= '#'ident
numeric_options ::= prefix | tag | counter | typename
string_options ::= prefix | tag
incr_options ::= numeric_options | increment
prefix    ::= ('PREFIX' string)?
tag       ::= ('TAG' string)?
counter   ::= ('COUNTER' local)?
typename  ::= ('TYPENAME' ident)?
increment ::= ('INCREMENT' expression)?
ident_list ::= '(' ident (',' ident)* ')'
constant_class ::= 'EQUALS' (expression numeric_options) | ('STRING' string string_options)
ident_equals ::= ident_list 'EQUALS' expression

constant ::= ('CONSTANT' ident constant_class)';' | ('CONSTANT' ident_list incr_options)';' | ('CONSTANT' ident_equals (',' ident_equals)*)';'
