printable ::= ' ' | '!' | '"' | '#' | '$' | '%' | '&' | "'" | '(' | ')' | '*' | '+' | ',' | '-' |
              '.' | '/' | [0-9] | ':' | ';' | '<' | '=' | '>' | '?' | '@' | [A-Z] | '[' | '\' | ']' |
              '^' | '_' | '`' | [a-z] | '{' | '|' | '}' | '~' | #x09| #x0A | #x0D
white_space ::= ' ' | [#x09-#x0D]

decimal ::= [0] | ('%'[dD] | [1-9])[0-9]*
hexidecimal ::= ('%' | [0])[xX][0-9a-fA-F]+
octal ::= ('%'[oO] | [0])[0-7]+
binary ::= '%'[bB][0-1]+
ascii ::= '%'[aA]([0-9][0-9][0-9] | [0-9A-Za-z][0-9A-Za-z])
string ::= '"' printable* '"'

name ::= [_$a-zA-Z][_$a-zA-Z0-9]*
variable ::= '#'name

expression ::= expr '+' terminal | expr '-' terminal | terminal

expr ::= expression

terminal ::= term '*' boolean | term '/' boolean | boolean

term ::= terminal

boolean ::= bool '&' bit_op | bool '|' bit_op | bit_op

bool ::= boolean
	
bit_op ::= bit '@' factor | factor

bit ::= bit_op

factor ::= '-' fact | '~' fact | '(' expression ')' | number | string

fact ::= factor

number ::= decimal | variable | hexadecimal | octal | binary | ascii | '.' | ':' | '^'
